### ISSUE TITLE
[Evolução] Criar ambiente único para desenvolvimento

### ISSUE THREAD

**Issue by J0a0Ceub** [Programacao-para-web-2023-01/ceublivre-api-infinite-monkey#6]
### Etapas do desenvolvimento

- [x] Criar arquivo de config do dev container
- [x] Criar documentação para o time (wiki)

### Descrever o problema a ser resolvido
Precisamos alinhar o ambiente de desenvolvimento que o time vai usar.

### Alternativas consideradas
Não tem

### Descreva a solução
Configurar o ambiente unificado via extensão do vscode (dev container) [https://containers.dev/].

**Comment by leandromqrs** [comment]
O ambiente foi configurado e já foi criado a página da Wiki para iniciar o desenvolvimento da ferramenta.

https://github.com/Programacao-para-web-2023-01/ceublivre-api-infinite-monkey/wiki/Configurar-Ambiente-de-Desenvolvimento
